//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PETSurv.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reports
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Reports()
        {
            this.OldReports = new HashSet<OldReports>();
        }
    
        public int Id { get; set; }
        public Nullable<int> ObservantsId { get; set; }
        public string Comment { get; set; }
    
        public virtual Observants Observants { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OldReports> OldReports { get; set; }
    }
}
